version: "2"
run:
  go: "1.24"
  modules-download-mode: readonly
linters:
  default: none
  enable:
#    - asasalint
#    - asciicheck
#    - bidichk
#    - canonicalheader
#    - containedctx
#    - contextcheck
#    - copyloopvar
#    - decorder
#    - dogsled
#    - dupword
#    - durationcheck
    - errcheck
    - errchkjson
    - errname
#    - errorlint
#    - exhaustive
#    - fatcontext
#    - forbidigo
#    - forcetypeassert
#    - funlen
#    - ginkgolinter
#    - gocheckcompilerdirectives
#    - gochecknoinits
#    - gochecksumtype
#    - gocognit
#    - goconst
#    - gocritic
#    - gocyclo
#    - godot
#    - gomoddirectives
#    - gomodguard
#    - goprintffuncname
#    - gosec
#    - gosmopolitan
#    - govet
#    - grouper
#    - importas
#    - inamedparam
#    - ineffassign
#    - interfacebloat
#    - lll
#    - loggercheck
#    - maintidx
#    - makezero
#    - mirror
#    - misspell
#    - musttag
#    - nakedret
#    - nestif
#    - nilerr
#    - nilnil
#    - noctx
#    - nolintlint
#    - nonamedreturns
#    - nosprintfhostport
#    - prealloc
#    - predeclared
#    - promlinter
#    - protogetter
#    - reassign
#    - revive
#    - rowserrcheck
#    - sloglint
#    - spancheck
#    - sqlclosecheck
#    - staticcheck
#    - tagliatelle
#    - testableexamples
#    - testifylint
#    - thelper
#    - tparallel
#    - unconvert
#    - unparam
#    - unused
#    - usestdlibvars
#    - wastedassign
#    - whitespace
#    - wrapcheck
#    - zerologlint
  settings:
    errcheck:
      check-type-assertions: true
      verbose: true
      exclude-functions:
        - github.com/spf13/viper.BindEnv
        - (*github.com/gorilla/websocket.Conn).SetReadDeadline
        - (*github.com/gorilla/websocket.Conn).SetWriteDeadline
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      # Module path which contains the source code being formatted.
      # Default: ""
      local-prefixes:
        - github.com/twofas/2fas-server
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
